data_cfg:
  name: mul
  root: ../OpenStereo/datasets/KITTI15
  train_list: ../OpenStereo/datasets/KITTI15/ylab-test.txt
  val_list: ../OpenStereo/datasets/KITTI15/val-combine-10.txt
  train_batch_size: 2
  # name: mul
  # root: datasets/KITTI15
  # train_list: datasets/KITTI15/kitti15_train20_mul.txt
  # val_list: datasets/KITTI15/kitti15_train20_mul.txt
  # test_list: datasets/KITTI15/kitti15_test.txt
  # train_batch_size: 1
#  name: KITTI2012
#  root: data/kitti12
#  train_list: datasets/KITTI12/kitti12_train194.txt
#  val_list: datasets/KITTI12/kitti12_train194.txt
#  test_list: datasets/KITTI12/kitti12_test.txt

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
      # - type: RandomCrop
        # size: [ 512, 512 ]
        size: [ 256, 512 ]
        # size: [ 256, 512 ]

        
        
      # - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      # - type: NormalizeImage
      #   mean: [ 0.485, 0.456, 0.406 ]
      #   std: [ 0.229, 0.224, 0.225 ]
        
      # - type: TransposeImage
      # - type: ToTensor
      # - type: NormalizeImage
      #   mean: [ 0.485, 0.456, 0.406 ]
      #   std: [ 0.229, 0.224, 0.225 ]
    val:
      - type: CropOrPad
        size: [ 480, 640 ]
        # size: [ 256, 512 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      # - type: NormalizeImage
      #   mean: [ 0.485, 0.456, 0.406 ]
      #   std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: MSNet_mul
  model_type: mul

  base_config:
    max_disp: 192
    # num_classes: 35
    num_classes: 19


loss_cfg:
  - log_prefix: seg
    loss_term_weight: 1
    type: CE_Loss
    weights: [ 1 ]
  - log_prefix: disp
    loss_term_weight: 1
    type: Weighted_Smooth_l1_Loss
    weights: [ 0.5, 0.5, 0.7, 1.0 ]
    



trainer_cfg:
  save_name: MSNet_mul_only_train_disp     #freeze_disp_seg_loss
  total_epoch: 300
  num_classes: 19
  restore_hint: 0
  optimizer_reset: false
  scheduler_reset: false
  warmup_reset: false
  log_iter: 5 # iter
  save_every: 5 # epoch
  val_every: 1 # epoch
  amp: false
  sync_bn: false
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: Adam
    lr: 0.001
    betas: [ 0.9, 0.999 ]

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.5
    milestones: [ 10, 12, 14, 16 ]
    warmup:
      warmup_steps: 100

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - bad_1
      - bad_2
      - bad_3
      - miou
      - f1

#  clip_grad_cfg:
#    #    type: norm
#    #    max_norm: 35
#    #    norm_type: 2
#    type: value
#    clip_value: 0.1